const c=document.getElementById("sim"),x=c.getContext("2d");let people=[],paused=false,infectChance=.12,defence=0,walls=[],roads=[];
function hit(a,b){return a.x+a.r>b.x&&a.x-a.r<b.x+b.w&&a.y+a.r<b.y+b.h&&a.y+a.r>b.y&&a.y-a.r<b.y+b.h}
function blocked(p,nx,ny){return walls.some(w=>hit({x:nx,y:ny,r:p.r},w))}
function makeCity(){walls=[];roads=[];const roadW=34;for(let i=0;i<4;i++){const yy=55+i*160+Math.random()*25;roads.push({x:0,y:yy,w:c.width,h:roadW})}for(let i=0;i<5;i++){const xx=70+i*180+Math.random()*25;roads.push({x:xx,y:0,w:roadW,h:c.height})}for(let i=0;i<18;i++){const w=55+Math.random()*80,h=45+Math.random()*75;let tries=0,b;do{b={x:20+Math.random()*(c.width-w-40),y:20+Math.random()*(c.height-h-40),w,h};tries++}while(tries<100&&roads.some(r=>b.x<r.x+r.w&&b.x+b.w>r.x&&b.y<r.y+r.h&&b.y+b.h>r.y));walls.push(b)}}
function reset(){people=[];makeCity();let n=+document.getElementById("count").value||45;for(let i=0;i<n;i++){let p={x:20+Math.random()*860,y:20+Math.random()*560,r:8,vx:0,vy:0,infected:false,defender:Math.random()<defence};let tries=0;while(walls.some(w=>hit(p,w))&&tries++<300){p.x=20+Math.random()*860;p.y=20+Math.random()*560}people.push(p)}if(people.length){people[0].infected=true;people[0].defender=false}}
function shoot(def,target){let dx=target.x-def.x,dy=target.y-def.y,d=Math.hypot(dx,dy)||1;def.vx+=dx/d*.018;def.vy+=dy/d*.018;return d<150&&Math.random()<.06}
function step(){for(const p of people){let target=null,md=1e9;if(p.infected){for(const q of people)if(!q.infected&&!q.dead){let d=Math.hypot(q.x-p.x,q.y-p.y);if(d<md){md=d;target=q}}}else if(p.defender){for(const q of people)if(q.infected&&!q.dead){let d=Math.hypot(q.x-p.x,q.y-p.y);if(d<md){md=d;target=q}}if(target&&shoot(p,target))target.dead=true}else{p.vx+=(Math.random()-.5)*.5;p.vy+=(Math.random()-.5)*.5}
if(target&&!p.dead){let dx=target.x-p.x,dy=target.y-p.y,d=Math.hypot(dx,dy)||1;if(p.infected){p.vx+=dx/d*.12;p.vy+=dy/d*.12}else if(p.defender){p.vx+=dx/d*.04;p.vy+=dy/d*.04}}
let sp=Math.hypot(p.vx,p.vy);if(sp>1.8){p.vx=p.vx/sp*1.8;p.vy=p.vy/sp*1.8}let nx=p.x+p.vx,ny=p.y+p.vy;if(blocked(p,nx,p.y)){p.vx*=-.8;nx=p.x}if(blocked(p,nx,ny)){p.vy*=-.8;ny=p.y}p.x=Math.max(p.r,Math.min(c.width-p.r,nx));p.y=Math.max(p.r,Math.min(c.height-p.r,ny))}
for(const a of people)if(a.infected)for(const b of people)if(!b.infected&&!b.dead){let d=Math.hypot(a.x-b.x,a.y-b.y);if(d<=16){b.infected=true;b.defender=false}else if(d<=30&&Math.random()<infectChance){b.infected=true;b.defender=false}}people=people.filter(p=>!p.dead)}
function draw(){x.clearRect(0,0,c.width,c.height);x.fillStyle="#27323a";x.fillRect(0,0,c.width,c.height);x.fillStyle="#46515a";for(const r of roads)x.fillRect(r.x,r.y,r.w,r.h);x.fillStyle="#6b7379";for(const w of walls){x.fillRect(w.x,w.y,w.w,w.h);x.fillStyle="#818990";x.fillRect(w.x+6,w.y+6,Math.max(4,w.w-12),4);x.fillStyle="#6b7379"}for(const p of people){x.beginPath();x.fillStyle=p.infected?"#35c759":p.defender?"#4da3ff":"#ffd83d";x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fill();x.fillStyle="#111";x.beginPath();x.arc(p.x-3,p.y-2,1.5,0,7);x.arc(p.x+3,p.y-2,1.5,0,7);x.fill();if(p.defender&&!p.infected){x.strokeStyle="#eaf6ff";x.lineWidth=3;x.beginPath();x.moveTo(p.x+5,p.y);x.lineTo(p.x+16,p.y);x.stroke()}}let inf=people.filter(p=>p.infected).length,def=people.filter(p=>p.defender&&!p.infected).length;document.getElementById("stats").textContent=`Population: ${people.length} | Infected: ${inf} | Healthy: ${people.length-inf} | Active defenders: ${def}`}
function loop(){if(!paused)step();draw();requestAnimationFrame(loop)}
document.getElementById("reset").onclick=reset;document.getElementById("pause").onclick=()=>{paused=!paused;document.getElementById("pause").textContent=paused?"RESUME":"PAUSE"};document.getElementById("count").oninput=e=>document.getElementById("countVal").textContent=e.target.value;document.getElementById("chance").oninput=e=>{infectChance=+e.target.value/100;document.getElementById("chanceVal").textContent=e.target.value+"%"};document.getElementById("defence").oninput=e=>{defence=+e.target.value/100;document.getElementById("defenceVal").textContent=e.target.value+"%";for(const p of people)if(!p.infected)p.defender=Math.random()<defence};reset();loop();